---
### Tasks for Role: nginx
# Enable Nginx Repository [RedHat/CentOS]
- name: nginx | Setup Nginx Yum Repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  when: ansible_os_family == "RedHat"
  tags: [nginx, repository]

# Enable Nginx Repository [Debian/Ubuntu]
- name: nginx | Setup Nginx APT Repository
  command: "{{ item }}"
  with_items:
    - /usr/bin/add-apt-repository -y ppa:nginx/stable
    - /usr/bin/apt-get update
  when: ansible_os_family == "Debian"
  tags: [nginx, repository]

# Install Nginx [RedHat/CentOS]
- name: nginx | Install the nginx packages 
  yum: name={{ item }} state=present
  with_items: redhat_pkg
  when: ansible_os_family == "RedHat"
  tags: [nginx, package]

# Install Nginx [Debian/Ubuntu]
- name: nginx | Install the nginx packages 
  apt: name={{ item }} state=present update_cache=yes
  with_items: ubuntu_pkg
  environment: env
  when: ansible_os_family == "Debian"
  tags: [nginx, package]

# Create default Nginx Dir
- name: nginx | Create /var/www
  action: file path=/var/www state=directory owner=nginx group=nginx mode=0755

# Create vhost config dir
- name: nginx | Create vhost config dir
  file: path=/etc/nginx/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "sites-available"
    - "sites-enabled"
  tags: [nginx, configuration]

# Nginx main configuration
- name: nginx | Setup nginx main configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: 
    - restart nginx
  tags: [nginx, configuration]

# Default Nginx configuration
- name: nginx | Setup default nginx configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  tags: [nginx, configuration]

# Default site configuration
- name: nginx | Setup default site configuration
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  tags: [nginx, configuration]

# Enable default site
- name: nginx | Enable default site
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default 
  tags: [nginx, configuration]

# Configure vhosts
- name: nginx | Setup Vhosts
  template: src=site.j2 dest=/etc/nginx/conf.d/{{ item['server']['file_name'] }}.conf
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
  notify: 
    - reload nginx
  tags: [nginx, configuration]

# Enable nginx service
- name: nginx | Enable nginx service
  service: name=nginx state=started enabled=yes
  tags: [nginx, service]
