---
### Tasks for Role: selinux
# Test if selinux is enabled
- name: selinux | test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
  tags: [selinux, validate]

- name: selinux | disable selinux
  command: /usr/sbin/setenforce 0
  when: sestatus != "Disabled"
  tags: [selinux, configuration]
  #ignore_errors: yes

- name: selinux | copy selinux config
  copy: src=selinux dest=/etc/selinux/config mode=0644
  tags: [selinux, configuration]
