---
### Tasks for Role: selinux
- name: selinux | disable selinux
  command: /usr/sbin/setenforce 0
  tags: [selinux, configuration]

- name: selinux | copy selinux config
  copy: src=selinux dest=/etc/selinux/config mode=0644
  tags: [selinux, configuration]
