---
galaxy_info:
  author: "Raghav Palekar"
  description: "Ansible role to install/setup nginx"
  company: "Remote System Support"
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all 
  - name: Debian
    versions:
    - all 
  categories:
  - system
  - web
dependencies: []
