---
galaxy_info:
  author: "Raghav Palekar"
  description: "Ansible role for configuring sysctl"
  company: "Remote System Support"
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  categories:
  - system
dependencies: []
