---
### Tasks for Role: httpd
# Install httpd
- name: httpd | Install httpd [Redhat/CentOS]
  yum: name={{ item }} state=installed
  with_items: httpd_pkgs
  tags: [httpd, package]

# Configure SELinux to allow httpd to connect to remote database
#- name: httpd | Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
#  when: sestatus.rc != 0 
#  tags: [httpd, configuration]

# Add iptables rule for httpd
- name: httpd | Add iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present
              regexp="{{ httpd_listen }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{ httpd_listen }} -j ACCEPT"
  notify: 
    - restart iptables
  tags: [httpd, firewall]

# Setup httpd config
- name: httpd | Setup httpd config
  template: src=httpd.conf.{{ ansible_os_family }}.j2 dest={{ httpd_conf_dir }}/httpd.conf
  notify: 
    - restart apache2
  tags: [httpd, configuration]

# Enable httpd service
- name: httpd | Enable httpd service
  service: name={{ httpd_service }} state=started enabled=true
  tags: [httpd, service]
